image: registry.c2bsoftware.com.br/c2b-gitlab-ci:latest

variables:
  DOCKER_DRIVER: overlay

services:
  - docker:dind

cache:
  paths:
    - node_modules/
    - dist/

stages:
  - unit_test
  - build-application

before_script:
  - cp /usr/app/.npmrc .

test_ci:
  stage: unit_test
  script:
    - yarn
    - yarn test

build_and_deploy:
  stage: build-application
  only:
    refs:
      - master
  script:
    - npm run build
    - docker build -t registry.c2bsoftware.com.br/__MUVEN-AGENT-NAME__:latest .
    - docker push registry.c2bsoftware.com.br/__MUVEN-AGENT-NAME__:latest
    - kubectl scale --replicas=0 deployment __MUVEN-AGENT-NAME__
    - kubectl scale --replicas=1 deployment __MUVEN-AGENT-NAME__
  artifacts:
    paths:
      - dist/
      - node_modules/